<#
.SYNOPSIS
  Read-only audit of the customized Android fork relative to the recorded
  iOS migration baseline. Produces a report under docs/updates/.

.DESCRIPTION
  Run from the iOS repository. Reads ANDROID-SOURCE-BASELINE.json, verifies the
  Android repository with READ-ONLY git operations, and:
    - in initial-full-migration mode: reports the snapshot/status WITHOUT implying
      a diff-only update is authoritative;
    - in incremental mode: compares lastAndroidCommitFullyPortedToIOS..HEAD and
      collects git evidence (log, diff --stat, diff --name-status, changed paths).

  SAFETY: never writes inside the Android repo; never updates the baseline; never
  modifies iOS source; never builds/checkouts/resets/cleans/stashes. The ONLY file
  it writes is the report under docs/updates/.

.OUTPUTS
  docs/updates/<UTC>-android-<shortsha>-audit.md

.NOTES
  Exit codes: 0 ok; 2 baseline missing/invalid; 3 Android path missing;
  4 not a git repo; 5 uncommitted tracked Android changes; 6 baseline commit
  not found in Android history.
#>

[CmdletBinding()]
param()

$ErrorActionPreference = 'Stop'

# Resolve the iOS repo root (parent of this tools/ dir) and operate from there.
$IosRoot = Split-Path -Parent $PSScriptRoot
Set-Location $IosRoot

function Fail($code, $msg) {
    Write-Error $msg
    exit $code
}

# Read-only git helper against an explicit repo path (never mutating).
function Git-RO {
    param([string]$RepoPath, [Parameter(ValueFromRemainingArguments = $true)] [string[]]$GitArgs)
    & git --no-pager -C $RepoPath @GitArgs 2>&1
}

# --- 1. Baseline ---------------------------------------------------------------
$baselinePath = Join-Path $IosRoot 'ANDROID-SOURCE-BASELINE.json'
if (-not (Test-Path $baselinePath)) { Fail 2 "Baseline not found: $baselinePath" }
try { $baseline = Get-Content $baselinePath -Raw | ConvertFrom-Json }
catch { Fail 2 "Baseline is not valid JSON: $($_.Exception.Message)" }

$androidPath  = $baseline.androidRepositoryPath
$mode         = $baseline.migrationMode
$incremental  = [bool]$baseline.incrementalUpdateModeEnabled
$snapshot     = $baseline.androidSourceSnapshotCommit
$fullyPorted  = $baseline.lastAndroidCommitFullyPortedToIOS

if ([string]::IsNullOrWhiteSpace($androidPath)) { Fail 2 'androidRepositoryPath missing in baseline.' }

# --- 2. Android repo sanity (read-only) ---------------------------------------
if (-not (Test-Path $androidPath)) { Fail 3 "Android repository path does not exist: $androidPath" }

$insideWorkTree = (Git-RO $androidPath 'rev-parse' '--is-inside-work-tree') -join "`n"
if ($LASTEXITCODE -ne 0 -or $insideWorkTree.Trim() -ne 'true') {
    Fail 4 "Not a git work tree: $androidPath"
}

$androidHead   = ((Git-RO $androidPath 'rev-parse' 'HEAD') -join "`n").Trim()
$androidBranch = ((Git-RO $androidPath 'branch' '--show-current') -join "`n").Trim()
$androidRemote = (Git-RO $androidPath 'remote' '-v') -join "`n"

# Tracked, uncommitted changes only (ignore untracked screenshots / aux files).
$trackedDirty = (Git-RO $androidPath 'status' '--porcelain' '--untracked-files=no') |
    Where-Object { $_ -and $_.Trim() -ne '' }

# --- 3. Verify recorded baseline commit(s) exist ------------------------------
function Commit-Exists($repo, $sha) {
    if ([string]::IsNullOrWhiteSpace($sha)) { return $false }
    & git --no-pager -C $repo cat-file -e "$sha^{commit}" 2>$null
    return ($LASTEXITCODE -eq 0)
}

$snapshotExists = Commit-Exists $androidPath $snapshot

# --- 4. Prepare report path ---------------------------------------------------
$utc      = (Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ')
$shortSha = if ($androidHead.Length -ge 7) { $androidHead.Substring(0,7) } else { $androidHead }
$updatesDir = Join-Path $IosRoot 'docs/updates'
if (-not (Test-Path $updatesDir)) { New-Item -ItemType Directory -Path $updatesDir -Force | Out-Null }
$reportPath = Join-Path $updatesDir "$utc-android-$shortSha-audit.md"

$report = New-Object System.Collections.Generic.List[string]
$report.Add("# Android update audit — $utc")
$report.Add('')
$report.Add('> Generated by tools/audit-android-update.ps1 (read-only). This report is')
$report.Add('> raw Git evidence plus a placeholder for later semantic classification by')
$report.Add('> Claude. It does NOT itself change any code or baseline.')
$report.Add('')
$report.Add('## Baseline (from ANDROID-SOURCE-BASELINE.json)')
$report.Add("- migrationMode: ``$mode``")
$report.Add("- incrementalUpdateModeEnabled: ``$incremental``")
$report.Add("- androidSourceSnapshotCommit: ``$snapshot`` (exists in Android: $snapshotExists)")
$report.Add("- lastAndroidCommitFullyPortedToIOS: ``$fullyPorted``")
$report.Add('')
$report.Add('## Android repository (read-only)')
$report.Add("- path: ``$androidPath``")
$report.Add("- HEAD: ``$androidHead``")
$report.Add("- branch: ``$androidBranch``")
$report.Add('- remotes:')
$report.Add('```')
$report.Add($androidRemote)
$report.Add('```')
$report.Add("- tracked uncommitted changes: " + ($(if ($trackedDirty) { 'YES' } else { 'none' })))

# Stop on uncommitted tracked Android changes (after recording them).
if ($trackedDirty) {
    $report.Add('')
    $report.Add('### ⚠️ Uncommitted tracked Android changes (audit halted)')
    $report.Add('```')
    $trackedDirty | ForEach-Object { $report.Add($_) }
    $report.Add('```')
    Set-Content -Path $reportPath -Value $report -Encoding UTF8
    Write-Host "Report: $reportPath"
    Fail 5 "Android has uncommitted tracked changes; commit them in the Android repo first. See $reportPath"
}

if (-not $snapshotExists) {
    $report.Add('')
    $report.Add('### ⚠️ Recorded snapshot commit not found in Android history')
    $report.Add("The baseline androidSourceSnapshotCommit ``$snapshot`` does not exist in the")
    $report.Add('Android repo (possible rewritten history). Do not trust diffs; re-establish')
    $report.Add('the baseline with the user before any synchronization.')
    Set-Content -Path $reportPath -Value $report -Encoding UTF8
    Write-Host "Report: $reportPath"
    Fail 6 "Recorded snapshot commit $snapshot not found in Android history. See $reportPath"
}

# --- 5. Mode-specific reporting ----------------------------------------------
$report.Add('')
if ($mode -eq 'initial-full-migration' -or -not $incremental) {
    $report.Add('## Mode: INITIAL FULL MIGRATION — diff-only update is NOT authoritative')
    $report.Add('')
    $report.Add('The initial full migration is not finalized. Differential (commit-to-commit)')
    $report.Add('synchronization must NOT be used yet. Future sessions must continue the full')
    $report.Add('migration using the Android snapshot as the COMPLETE behavioral reference')
    $report.Add('(see CONTINUE-INITIAL-MIGRATION.md). Unchanged Android files are NOT assumed')
    $report.Add('already ported.')
    $report.Add('')
    $report.Add("- Android HEAD == snapshot? " + ($(if ($androidHead -eq $snapshot) { 'yes' } else { "no (HEAD $shortSha vs snapshot $($snapshot.Substring(0,7)))" })))
    if ($androidHead -ne $snapshot) {
        $report.Add('')
        $report.Add('### FYI: commits since the recorded snapshot (informational only)')
        $report.Add('```')
        (Git-RO $androidPath 'log' '--oneline' "$snapshot..HEAD") | ForEach-Object { $report.Add($_) }
        $report.Add('```')
        $report.Add('> Informational only — do NOT treat as the synchronization unit while in')
        $report.Add('> initial-full-migration mode.')
    }
}
else {
    $report.Add('## Mode: INCREMENTAL SYNCHRONIZATION')
    if (-not (Commit-Exists $androidPath $fullyPorted)) {
        $report.Add('')
        $report.Add("### ⚠️ lastAndroidCommitFullyPortedToIOS ``$fullyPorted`` not found in Android history")
        $report.Add('Cannot compute a trustworthy diff. Re-establish the baseline with the user.')
        Set-Content -Path $reportPath -Value $report -Encoding UTF8
        Write-Host "Report: $reportPath"
        Fail 6 "Fully-ported commit $fullyPorted not found in Android history. See $reportPath"
    }
    $range = "$fullyPorted..$androidHead"
    $report.Add("- Comparison range: ``$range``")
    $report.Add('')
    $report.Add('### git log')
    $report.Add('```'); (Git-RO $androidPath 'log' '--oneline' $range) | ForEach-Object { $report.Add($_) }; $report.Add('```')
    $report.Add('### git diff --stat')
    $report.Add('```'); (Git-RO $androidPath 'diff' '--stat' $range) | ForEach-Object { $report.Add($_) }; $report.Add('```')
    $report.Add('### git diff --name-status')
    $report.Add('```'); (Git-RO $androidPath 'diff' '--name-status' $range) | ForEach-Object { $report.Add($_) }; $report.Add('```')
}

# --- 6. Classification placeholder for Claude ---------------------------------
$report.Add('')
$report.Add('## Semantic classification (to be completed by Claude)')
$report.Add('- [ ] behavioral changes to port to iOS')
$report.Add('- [ ] Android-platform-only changes to ignore')
$report.Add('- [ ] backend/schema/anki-pin changes')
$report.Add('- [ ] tests/docs/feature-map updates required')
$report.Add('- [ ] licensing impact')

Set-Content -Path $reportPath -Value $report -Encoding UTF8
Write-Host "migrationMode: $mode"
Write-Host "Android HEAD:  $androidHead ($androidBranch)"
Write-Host "Snapshot:      $snapshot (exists: $snapshotExists)"
Write-Host "Report:        $reportPath"
exit 0
